// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPersonalWebsite.Data;

#nullable disable

namespace MyPersonalWebsite.Data.Migrations
{
    [DbContext(typeof(PersonalWebDbContext))]
    partial class PersonalWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryKeyValue")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.GenericList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GenericLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "100",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5902),
                            IsActive = true,
                            Name = "Adet",
                            TypeName = "Miktar"
                        },
                        new
                        {
                            Id = 2,
                            Code = "101",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5904),
                            IsActive = true,
                            Name = "Koli",
                            TypeName = "Miktar"
                        },
                        new
                        {
                            Id = 3,
                            Code = "103",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5906),
                            IsActive = true,
                            Name = "Paket",
                            TypeName = "Miktar"
                        },
                        new
                        {
                            Id = 4,
                            Code = "104",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5908),
                            IsActive = true,
                            Name = "Palet",
                            TypeName = "Miktar"
                        },
                        new
                        {
                            Id = 5,
                            Code = "200",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5910),
                            IsActive = true,
                            Name = "Kg",
                            TypeName = "Ağırlık"
                        },
                        new
                        {
                            Id = 6,
                            Code = "201",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5912),
                            IsActive = true,
                            Name = "Ton",
                            TypeName = "Ağırlık"
                        });
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.MaterialInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MaterialInformations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1000000",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5829),
                            Description = "",
                            IsActive = true,
                            Name = "Dell Insprion 5515 Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Code = "1000002",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5832),
                            Description = "",
                            IsActive = true,
                            Name = "Apple Macbook Pro 13"
                        },
                        new
                        {
                            Id = 3,
                            Code = "1000003",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5834),
                            Description = "",
                            IsActive = true,
                            Name = "MSI 32 Curve Monitor"
                        },
                        new
                        {
                            Id = 4,
                            Code = "1000004",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5836),
                            Description = "",
                            IsActive = true,
                            Name = "Microsoft Mouse"
                        },
                        new
                        {
                            Id = 5,
                            Code = "1000005",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5838),
                            Description = "",
                            IsActive = true,
                            Name = "Windows 11 Kutulu Lisans"
                        },
                        new
                        {
                            Id = 6,
                            Code = "1000006",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5840),
                            Description = "",
                            IsActive = true,
                            Name = "100 Watt Type C Adaptör"
                        });
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderNo")
                        .IsUnique();

                    b.HasIndex("MaterialId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "100",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5755),
                            Description = "Sipariş Alındı",
                            IsActive = true,
                            Name = "Sipariş Alındı"
                        },
                        new
                        {
                            Id = 2,
                            Code = "101",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5759),
                            Description = "Yola Çıktı",
                            IsActive = true,
                            Name = "Yola Çıktı"
                        },
                        new
                        {
                            Id = 3,
                            Code = "102",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5761),
                            Description = "Dağıtım Merkezinde",
                            IsActive = true,
                            Name = "Dağıtım Merkezinde"
                        },
                        new
                        {
                            Id = 4,
                            Code = "103",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5763),
                            Description = "Dağıtıma Çıktı",
                            IsActive = true,
                            Name = "Dağıtıma Çıktı"
                        },
                        new
                        {
                            Id = 5,
                            Code = "104",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5765),
                            Description = "Teslim Edildi",
                            IsActive = true,
                            Name = "Teslim Edildi"
                        },
                        new
                        {
                            Id = 6,
                            Code = "105",
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5768),
                            Description = "Teslim Edilemedi",
                            IsActive = true,
                            Name = "Teslim Edilemedi"
                        });
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivationHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BadLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivationHash = "",
                            BadLoginAttempts = 0,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5609),
                            Email = "eyyub.tezcan@gmail.com",
                            EncryptedPassword = "",
                            ExpireDate = new DateTime(2023, 4, 13, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5603),
                            IsActive = false,
                            LastName = "",
                            Name = "System",
                            PhoneNumber = "",
                            UserName = "System"
                        },
                        new
                        {
                            Id = 2,
                            ActivationHash = "",
                            BadLoginAttempts = 0,
                            CreatedById = 1,
                            CreatedDate = new DateTime(2023, 3, 14, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5613),
                            Email = "eyyub.tezcan@gmail.com",
                            EncryptedPassword = "",
                            ExpireDate = new DateTime(2023, 4, 13, 8, 37, 51, 207, DateTimeKind.Local).AddTicks(5612),
                            IsActive = true,
                            LastName = "Tezcan",
                            Name = "Eyyüb",
                            PhoneNumber = "05375140784",
                            UserName = "eyyub.tezcan@gmail.com"
                        });
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.Order", b =>
                {
                    b.HasOne("MyPersonalWebsite.Data.Entities.MaterialInformation", "Material")
                        .WithMany("Orders")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPersonalWebsite.Data.Entities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.MaterialInformation", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MyPersonalWebsite.Data.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
